compressionLevel: mixed

enableGlobalCache: true

nodeLinker: pnp

packageExtensions:
  babel-plugin-relay@*:
    dependencies:
      "@babel/runtime": "*"
      graphql: ^16.8.1
  local-pkg@*:
    dependencies:
      happy-dom: "*"
  kanel-zod@*:
    dependencies:
      kanel: "*"
      ramda: "*"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.0.2.cjs
