compressionLevel: mixed

enableGlobalCache: true

nodeLinker: pnp

packageExtensions:
  babel-plugin-relay@*:
    dependencies:
      "@babel/runtime": "*"
      graphql: ^16.8.1
  kanel-zod@*:
    dependencies:
      kanel: "*"
      ramda: "*"
  local-pkg@*:
    dependencies:
      happy-dom: "*"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.1.0.cjs
