enableGlobalCache: true

nodeLinker: pnp

packageExtensions:
  "local-pkg@*":
    dependencies:
      "happy-dom": ^9.20.3
  "@miniflare/r2@*":
    dependencies:
      "@miniflare/core": ^2.14.0
  babel-plugin-relay@*:
    dependencies:
      "@babel/runtime": ^7.22.0

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.0.0-rc.44.cjs
