compressionLevel: mixed

enableGlobalCache: true

nodeLinker: pnp

packageExtensions:
  babel-plugin-relay@*:
    dependencies:
      "@babel/runtime": "*"
  local-pkg@*:
    dependencies:
      happy-dom: "*"
  vite-plugin-relay@*:
    dependencies:
      babel-plugin-relay: ^15.0.0

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.0.0-rc.52.cjs
