enableGlobalCache: true

nodeLinker: pnp

packageExtensions:
  "@miniflare/r2@*":
    dependencies:
      "@miniflare/core": ^2.14.0
  babel-plugin-relay@*:
    dependencies:
      "@babel/runtime": ^7.22.5
  local-pkg@*:
    dependencies:
      happy-dom: ^9.20.3

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.0.0-rc.45.cjs
