version: '3'

services:

  api:
    image: node:7.7.2-alpine
    restart: always
    env_file: .env
    links:
      - postgres
      - redis
    ports:
      - $PORT:$PORT
      - '127.0.0.1:9229:9229' # V8 inspector
    volumes:
      - yarn:/root/.cache/yarn
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: node scripts/run.js

  postgres:
    image: postgres:9.6.2-alpine
    restart: always
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./scripts/postgres-init.sh:/docker-entrypoint-initdb.d/init.sh

  redis:
    image: redis:3.2.8-alpine
    restart: always
    read_only: true
    volumes:
      - redis:/data

volumes:
  yarn:
  postgres:
  redis:
